name: SecondStoryLive
version: '1.0'
api-version: "1.13"
main: me.syari.sec_story.paper.live.Main
author: sya_ri
depend:
  - SecondStoryLibrary
  - MythicMobs
  - CrackShot
  - CrackShotPlus
  - FastAsyncWorldEdit